pipeline {
    agent {
        docker {
            image 'python:3.6.12-alpine'
        }
    }

    stages {
        stage('build') {
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install -r requirements.txt --user'
                }
            }
        }
        stage('test') {
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Running tests'
                dir('vote') {
                    sh 'nosetests -v'
                }
            }
        }
    }
    
    post {
        always{
            echo "Finished!"
        }
    }
}

