pipeline {
    agent none

    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:3.6.12-alpine'
                    args '--user 0:0'
                }
            }
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install --no-cache -r requirements.txt'
                }
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:3.6.12-alpine'
                    args '--user 0:0'
                }
            }
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Running tests'
                dir('vote') {
                    sh 'pip install --no-cache -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package') {
            agent any // Work in jenkins host
            when {
                changeset '**/vote/**'
                branch 'master'
            }
            steps {
                echo 'Packaging vote app with Docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                         def workerImage = docker.build("lgomezdevartis/vote:${env.BUILD_ID}", "./vote")
                         workerImage.push()
                         workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }
    
    post {
        always{
            echo "Finished!"
        }
    }
}

