pipeline {
    agent none

    stages {
        stage('build') {
            agent {
                docker {
                    image 'maven:3.6.1-jdk-8-alpine'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'maven:3.6.1-jdk-8-alpine'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }

            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running tests'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('docker-package') {
            agent any // Work in jenkins host
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging worker app with Docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {
                         def workerImage = docker.build("repositories/worker:${env.BUILD_ID}", "./worker")
                         workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }
    
    post {
        always{
            echo "Finished!"
        }
    }
}

